### ISSUE TITLE
Text disappears in Dark Mode

### ISSUE THREAD

**Issue by 2unbini** [2unbini/pple#74]
텍스트 색상을 검은색으로 해 놓은 것들이 다크 모드에서 제대로 보이지 않는 현상

**Comment by skkimeo** [comment]
은빈님 저도 이거 같은 이슈 있어서 생각한건데 저희 그러면 isFinished 면 회색으로 바뀌게 한 것도 다크모드 때는 그대로 갈 지 아님 좀 바꿀지 얘기해봐야 할 거 같아😂
