### ISSUE TITLE
UI - Project Calendar View

### ISSUE THREAD

**Issue by 2unbini** [2unbini/pple#9]
- 프로젝트 캘린더 뷰
    - 캘린더
    - 한 줄에 7일
       - 7일보다 적으면 그 개수만큼 맞춰서
       - 그것보다 많으면 테트리스처럼 보일 수 있다.

**Comment by tekim-526** [comment]
한줄에 7일이 되어버리면 너무 작아져서 한줄에 5줄로 맞추었습니다!
